### ISSUE TITLE
how to send binary data

### ISSUE THREAD

**Issue by zhangyi** [luvit/luv#117]
the code like this : 

local socket = uv.new_tcp()
uv.tcp_connect(socket , host, port, function (err)
    //send binary buffer
    uv.write(socket , buffer)
end)

the buffer use lpack To obtain.  lpack link >> http://underpop.free.fr/l/lua/lpack/

**Comment by imzyxwvu** [comment]
so what's the problem? lua strings are just immutable binary buffers. simply write what you got from lpack is enough. you just need to call uv.run() to get everything working.

**Comment by creationix** [comment]
As was said, lua strings are already binary data.  The luv APIs all work with strings as binary data.  If you want to use lpack to help build a properly formatted string that is fine, but in the end, it's just a string the same as any other in lua.  Nothing special is needed on the uv side.
