### ISSUE TITLE
Rockspec fails with 'Mandatory field source is missing'

### ISSUE THREAD

**Issue by daurnimator** [luvit/luv#124]
```
$ sudo luarocks install luv
[sudo] password for daurnimator:
Installing https://rocks.moonscript.org/luv-1.4.2-1.rockspec...
Using https://rocks.moonscript.org/luv-1.4.2-1.rockspec... switching to 'build' mode

Error: /tmp/luarocks_luarocks-rockspec-luv-1.4.2-1-704/luv-1.4.2-1.rockspec: Mandatory field source is missing.
```

This is a symptom of only testing with `luarocks make` :)

**Comment by creationix** [comment]
Actually it's a bit more involved than that. https://github.com/luvit/luv/pull/123

I guess it finally cleared the cache and used the lastest version I uploaded which was missing the source field. (After uploading I tested and it gave a very different error)

**Comment by creationix** [comment]
Fixed now uploaded tarball to https://github.com/luvit/luv/releases/download/1.4.2-2/luv-1.4.2-2.tar.gz and updated manifest on luarocks.
