### ISSUE TITLE
Building luv

### ISSUE THREAD

**Issue by joerg-krause** [luvit/luv#134]
I'm trying to ease the library dependency for building luv with Buildroot. For this, I want to build luv with libuv and lujit as external libraries (not the one in deps/) as package dependency is handled by Buildroot. I added simple FindLibuv.cmake and FindLuaJIT.cmake files to locate the libraries with find_package.

I would suggest to remove the `git submodule` part in both Makefiles and CMakelists.txt. For a build system it's not applicable and if a user follows the README it's not necessary.

What I would do instead is: if find_package does not find a library in the build environment it will call the cmake files for the deps.

What do you think?

**Comment by creationix** [comment]
The submodules are great because they also document the exact hash to use the target repos.  I understand they are a pain for some workflows.

I put it in the cmake file to make luarocks work, but I don't think it's needed anymore since my luarocks deploy moved to using a tarball instead of git.

If you want to send a PR for your find scripts, I can look at it.  Just be aware of the travis, appveyor and luarocks workflows I already have (in addition to human driving via makefile).

**Comment by joerg-krause** [comment]
There's nothing wrong with submodules. They are a great way to add external repositories as dependencies to your own project.

What I mean is that dependency handling like checkout/cloning submodules is not the task of the project build files, but of the builder. Of course the builder needs instructions about how to build and what dependencies are needed. This fits well in the way systems like Buildroot or OpenWrt uses package management. E.g. in Buildroot you define that luv depends on libuv and luajit and the build system takes care that both are build before luv.

Furthermore it adds the possibility to link against shared libraries. The find_package command tries to locate if a given library is already installed on your system and cmake uses this lib for linking.

I will send you a PR. I left the submodules parts untouched, so it's up to you to remove them.

**Comment by joerg-krause** [comment]
Another question. What is the reason for why luv is not install as libluv?

**Comment by joerg-krause** [comment]
Unintentionally closed - reopened.

**Comment by creationix** [comment]
I merged the PR, does this work for you now?

**Comment by joerg-krause** [comment]
Thanks! This works, but I have two remarks: 

1. As I commented the variables `Libuv_INCLUDE_DIRS` must be `LIBUV_INCLUDE_DIR` and `LuaJIT_INCLUDE_DIRS` must be `LUAJIT_INCLUDE_DIR`.
2. Since the git submodule check is not necessary anymore, I would like to remove it from the CMakeLists.txt for the reasons I stated above.

I will send you another PR...

**Comment by joerg-krause** [comment]
Send another PR targeting the issues mentioned in my previous comment: https://github.com/luvit/luv/pull/139

Issue can be closed now.
