### ISSUE TITLE
"make test" not passed on osx 

### ISSUE THREAD

**Issue by sfszh** [luvit/luv#137]
os version: osx 10.10.2
luajit version: 2.0.3
do: make test
got:
Linking C shared module luv.so
[100%] Built target luv
ln -sf build/luv.so
build/luajit tests/run.lua
build/luajit: error loading module '/luv' from file './/luv.so':
	dlsym(0x7f8033404bd0, luaopen_/luv): symbol not found
stack traceback:
	[C]: at 0x010696fc70
	[C]: in function 'require'
	tests/run.lua:7: in main chunk
	[C]: at 0x0106936350
make: *** [test] Error 1

**Comment by creationix** [comment]
Are you still getting this is latest luv?  I can't reproduce it locally.
