### ISSUE TITLE
Is there any easy way to using luv/luvi/luvit with Lua5.3?

### ISSUE THREAD

**Issue by starwing** [luvit/luv#147]
Hi,

this projects is very interesting :) I have built it from source without any issue. and the bundle idea is GREAT!!

As I use PUC Lua for my daily work. I want to get some information about it:
  - can I (personally) change it's LuaJIT to PUC Lua 5.3 easily?
  - If I do that, can I put some so/dlls into bundle? and how luvit work in this way?
  - or, is there any other way to use extenal dll libraries for Lua?

I built all my modules againest Lua5.3, So change Lua in luvi seems easiler. Just wonder whether a way exits.

thanks!

**Comment by imzyxwvu** [comment]
Only the binding for libuv could work with PUC Lua. luvit is highly based on luajit and lua 5.1. For now there is no way to bundle Lua C libraries. The best way to call C code is the luajit C ffi.

**Comment by creationix** [comment]
There are a few places in luvi and luvit that assume luajit semantics.  The hardest one would be the ffi interface (unless there is a C replacement like there is for the bit.* apis).

Luvit's require system can load binary addons from the bundle and lit supports publishing binary libraries to the public database.

When you try to require a .so/.dll from the bundle, luvi will extract it to a temporary file, dlopen it and delete the temporary file.  This is the same technique java jar files use so it's pretty well tested.

https://github.com/luvit/lit/wiki/Publishing-Compiled-Code

**Comment by creationix** [comment]
I will say that the luv (libuv bindings for lua) are engine agnostic and should work with PUC lua 5.3, if not, file an issue and I'll fix it, it's a supported use case.

https://github.com/luvit/luv

Also the "luvit" project is just a set of lua libraries on top of luvi.  You might be able to reuse them with minimal modification using luv and stock lua (basically skipping the whole luvi layer).  You'd have to either create replacements for the luvi APIs or modify the luvit libraries that use luvi APIs.

**Comment by creationix** [comment]
See also luvit/luvit#682

**Comment by starwing** [comment]
@creationix Thank you for your detail explains :)

I have found some imcompatible with Lua5.3, and make a pull request about that.
btw, I tweak the build script so that PUC Lua is included into source, and we can choose build luv against with PUC Lua in cmake options.

The news about support binary module is great! I will try to build some of my modules (mainly about charset) to luvit.

thanks :)

**Comment by creationix** [comment]
Thanks to some community PRs and some more fixes I made, luv is now building and testing luajit **and** lua 5.3 on travis after every commit.  This should help is maintain compatibility going forward.

**Comment by creationix** [comment]
I'm not explicitly testing for lua 5.1, but most things that work on both luajit and lua 5.3 are likely to also work on lua 5.1.

**Comment by creationix** [comment]
Also I think I've published an updated luv (v1.6.1-2) to luarocks.  I don't fully understand that system.

**Comment by starwing** [comment]
@creationix Thank you very much for this excellent job!

So, It's not difficult to make a lua5.3 compatible version of luv now, is there any difficult to make Lua5.3 version of luvi/lit/luvit works?

**Comment by creationix** [comment]
Using puc Lua for luvi is a little harder, but I think it can be done.

-----Original Message-----

**Comment by creationix** [comment]
One thing to keep in mind is luv is lower-level and officially supports PUC Lua.  Luvi is higher-up the abstraction chain and has more opinions.  I'll try to make it run on other luas, but it might not be a fully supported use case.
