### ISSUE TITLE
Sample from README.md gives error

### ISSUE THREAD

**Issue by rafis** [luvit/luv#150]
I ran sample with timer, which prints "Awake!" after 1000ms, on Windows it gives an error:

> Uncaught Error: test-timer.lua:11: bad argument #1 to 'close' (Expected uv_handle userdata)

`timer`'s value is `nil`.

**Comment by creationix** [comment]
Thanks for catching this, sorry if it caused you trouble.

A long time ago, the callbacks had the handle as the first arg, we later removed this and I forgot to update the README.

Also we later added method syntax to most uv functions and so I've updated the README to use the clearer method syntax.  You can still use the old C style interface if you prefer explicitly passing in the handle.
