### ISSUE TITLE
uv.fs_lstat on Windows not returning sb.type == "link"

### ISSUE THREAD

**Issue by brimworks** [luvit/luv#153]
```sb = uv.fs_lstat()``` was not returning ```sb.type == "link"``` on windows, instead it was returning ```nil```. After some investigation, I found out that ``./include/uv-win.h``` defines S_IFLNK and therefore the S_ISLNK() macro can be defined as such:

```diff
diff --git a/src/luv.h b/src/luv.h
index c3217a1..db52d55 100644
--- a/src/luv.h
+++ b/src/luv.h
@@ -33,7 +33,7 @@
 # define S_ISFIFO(x) (((x) & _S_IFMT) == _S_IFIFO)
 # define S_ISCHR(x)  (((x) & _S_IFMT) == _S_IFCHR)
 # define S_ISBLK(x)  0
-# define S_ISLNK(x)  0
+# define S_ISLNK(x)  (((x) & S_IFLNK) == S_IFLNK)
 # define S_ISSOCK(x) 0
 #else
 # include <unistd.h>
```

I've verified that this fixes the windows incompatibility issue.

**Comment by rphillips** [comment]
PR'ed it so we can try it on the buildbots
