### ISSUE TITLE
Incomplete v1.6.1 source tarball

### ISSUE THREAD

**Issue by joerg-krause** [luvit/luv#166]
The source tarball is missing some directories and files. eg. the entire directory `cmake`, and some files and directories in `deps`.

**Comment by creationix** [comment]
I see, some new files were added since I wrote the script.   You don't need/want the source to lua and luajit do you?  This tarball is designed for use by luarocks where you already have lua and just want the addon.

**Comment by joerg-krause** [comment]
No, I do not necessarily need lua and luajit, but they don't hurt. Important is the `cmake` directory. Thanks!

**Comment by creationix** [comment]
I updated the tarball.  Let me know if this works for you.

**Comment by joerg-krause** [comment]
Many thanks! However, the tarball does not contain the snapshot of commit 304589a0b2bc7c025d1a3a4faf8038c9d5ce7b10 (which is tag https://github.com/luvit/luv/tree/v1.6.1) but of the latest master commit 55d81e9ea39db83492d5e15720be4738d7e6a2ba.

**Comment by creationix** [comment]
Re-uploaded.

**Comment by joerg-krause** [comment]
Thanks! Works well.
