### ISSUE TITLE
Windows: Second Client Read - EBADF

### ISSUE THREAD

**Issue by brimworks** [luvit/luv#177]
Run this code on Windows:

https://gist.github.com/brimworks/c129c707044359d30ed7

This results in an infinite loop of errors:

```
ERROR:  [string "bundle:main.lua"]:27: EBADF
stack traceback:
        [C]: in function 'error'
        [string "bundle:main.lua"]:27: in function 'check'
        [string "bundle:main.lua"]:39: in function <[string "bundle:main.lua"]:35>
        [C]: in function 'xpcall'
        [string "bundle:main.lua"]:15: in function <[string "bundle:main.lua"]:14>
```

On Mac this prints what you would expect:

```
Hello World 1
Hello World 2
DONE
```

Note that if you change this code:

```lua
for idx=1,2 do
    ...
end
```

So it goes from 1 to 1, everything works fine. I'm still digging into this to see if it is a problem with libuv.

Thanks,
-Brian

**Comment by brimworks** [comment]
Note that this is a binary that exhibits this behavior:

https://github.com/luvit/luvi/releases/download/v2.2.0/luvi-regular-Windows-amd64.exe

...2.1.8 appears to work fine. Based on the release notes, it is probably caused by "libuv: update to v1.7.0"

**Comment by brimworks** [comment]
Relevant diff: https://github.com/libuv/libuv/compare/30c8be07bb78a66fdee5141626bf53a49a17094a...415a865d6365ba58d02b92b89d46ba5d7744ec8b

...I will probably end up needing to file this bug with the libuv team.

**Comment by rphillips** [comment]
it might be possible to git bisect further into that diff.

**Comment by brimworks** [comment]
I ran `git bisect` and it places blame on this change:

https://github.com/libuv/libuv/commit/fb5df542ace7d6735a9e8e09d7d8bb6b8abdc459

...obviously this is a bug in libuv :). I'll see if I can figure out the problem and file a bug with libuv.

Thanks,
-Brian

**Comment by brimworks** [comment]
...and more specifically the two lines added to src/win/pipe.c within that commit trigger the bad behavior.

**Comment by creationix** [comment]
Thanks for digging in.

**Comment by brimworks** [comment]
More digging in has been placed here:

https://github.com/libuv/libuv/pull/400

...but maybe I should just open a separate issue with the libuv team.

**Comment by brimworks** [comment]
Closing in favor of this issue: https://github.com/libuv/libuv/issues/485

Thanks,
-Brian
