### ISSUE TITLE
Passing async from thread

### ISSUE THREAD

**Issue by mkschreder** [luvit/luv#182]
I want to pass data back from a thread using async_send and apparently thread does not accept userdata async handle that you get from new_async(). How can I do this? 

local uv = require("luv");

local var = uv.new_async(function(str)
        print("Hello from async!: ", str); 
end);                

local foo = uv.new_async(function() print("internal async"); end);
local thread = uv.new_thread(function(var)  
        local uv = require("uv");  
        print("Hello from thread!");
        uv.async_send(var, "hello");  
end, var); -- < this fails 

uv.run(); 
uv.thread_join(thread);

**Comment by creationix** [comment]
@zhaozg do you know the answer to this question?

@mkschreder George is in China timezone I believe so it might be a while till he responds.

**Comment by mkschreder** [comment]
I have sortof managed to do what I want by patching thread.c and async.c
and using new_work() to pass an object with data that is used to invoke a
blocking call and passing the result back to the caller. Problem I had was
that I got an error when passing anything other than basic lua types to
thread func.

Basically what I want to do is pretty basic. I want to pass arbitrary data
to a thread that will issue blocking calls and invoke async callback for
progress and then another async callback upon completion. It obviould needs
to be able to pass data to these callbacks. And I also want to be able to
pass async messages to a running thread. Should be pretty simple, but
apparently it's not.. :-)

**Comment by creationix** [comment]
Sounds like reasonable requirements.  I'd like something like that as well.  Did you see the recent worker thread pool created by George? https://github.com/luvit/luv/pulls?q=is%3Apr+is%3Aclosed

I haven't had time yet to sit and try out the new thread stuff, consider it experimental, but exciting!

**Comment by zhaozg** [comment]
I'll fix it in three days, please wait. 
And in my memory, async notify is not safe because some notify will lost, or you accept the risk.

**Comment by zhaozg** [comment]
@mkschreder 
according to http://docs.libuv.org/en/v1.x/async.html, uv_async_t work as notify with out paramater, to pass data, I agree @creationix 's option, you should use uv.new_work uv.queue_work.

```lua
local uv = require("luv");

local var = uv.new_async(function(str)  --not support accept paramater
print("Hello from async!: ", str); 
end);
uv.async_send(var, "hello"); -- can't pass any data
```
please ref to https://github.com/luvit/luv/blob/master/docs.md#uv_async_t--async-handle

**Comment by mkschreder** [comment]
@zhaozg, you CAN pass data with async. The uvasync struct has a data field in it. They even have an example of how to do it in uv docs in section about interthread communication. What use is async otherwise if you can not pass progress data with it? 

To make it fully safe we should restrict the data to basic types (string int etc) and always copy it when it is passed and deleting it after it has been received (in luv). The only "userdata" that makes sense to pass to a thread is the handle to this async object so that it can be invoked from inside the thread with data. 

The idea is that you would then use json to pass more complex objects as strings, and anything that can not be converted to json should not be passed between threads anyway. This json conversion can be done on application level though. Luv just needs to support passing a string to async like you showed above.

**Comment by mkschreder** [comment]
No it is simply that if you send multiple notifications during the same
loop, uv will only invoke your callback once. This is expected behavior.
Nothing unsafe about it in my opinion.

**Comment by mkschreder** [comment]
Async does however guarantee that your callback will be called AT LEAST
once :-)

**Comment by zhaozg** [comment]
@mkschreder 

> you CAN pass data with async.

We need to hack luv to support that.

> The only "userdata" that makes sense to pass to a thread is the handle to this async object.

Yes, async object use to do INPROC, it has high property than others. 

> The idea is that you would then use json.

I keep this point too.

**Comment by mkschreder** [comment]
Luv does not seem to support passing parameters with async yet. But here is
an example of how it can be done directly with libuv:
http://nikhilm.github.io/uvbook/threads.html

percentage = downloaded*100.0/size;
        async.data = (void*) &percentage;
        uv_async_send(&async);

In lua it would be reasonable however to make data an internal luv object
through which multiple arguments can be passed through async callback.

usage would be uv.async_send("string", 10, true,..).

**Comment by zhaozg** [comment]
Find solution, and make RP would be more efficient, although I accept you point.

**Comment by mkschreder** [comment]
Hacking in progress here already :-) I've just never used lua api before so
I'm learning it in the process. Need to make sure I free everything
correctly and such. So I think George or someone else who knows the api
inside out would implement this a lot faster and better :-)

**Comment by zhaozg** [comment]
haha, @creationix  and @rphillips are good teacher, please enjoy lua(jit)

**Comment by mkschreder** [comment]
:D

**Comment by zhaozg** [comment]
Pass userdata between threads are really not easy, almost broken my head.

**Comment by mkschreder** [comment]
No what I mean is strictly the userdata object in lua. But it should be
restricted only to a few types of "userdata". Such as handle to async.
Since async is threadsafe for as long as you don't poke around inside the
data pointer from multiple threads at once (which is solved by copying
data). Actually there was already sortof support for passing async handle
to thread in luv, but it didn't work. I have fixed it here already:
https://github.com/mkschreder/luv

So now I can do things like this:
https://github.com/mkschreder/luci-express/blob/devel/examples/uv-async-threading-example.lua

It works alright, but I still noticed that if I repeatedly create many
threads (even if they exit quickly), eventually my program runs out of file
descriptors even though no more than 10 threads are running at once..
Although I don't think it is related to my changes. It is something else in
the backend that is not freeing stuff.. will have to debug it a bit more..
:-)

**Comment by zhaozg** [comment]
> runs out of file descriptors

are you apply this patch https://github.com/luvit/luv/commit/66936e7612f93c898c2c775edc5b77752374141c,

or please make https://github.com/mkschreder/luci-express/blob/devel/examples/uv-async-threading-example.lua#L16 (local work) to (work) try again.

**Comment by mkschreder** [comment]
That was a slightly different file actually. Here is a better example. I managed to make it work like this. But the only thing missing now is passing data as parameter to async invocation. Then it would be perfect  :-) 

https://github.com/mkschreder/luci-express/blob/devel/examples/uv-async-from-thread.lua

Output: 
In thread. Got arg: Hello World!
Async notification for 'progress' event
Long task progress: async progress: 
Async notification for 'progress' event
Long task progress: async progress: 
...
Async notification for 'done' event
Long task done. Got result: string from async done:

**Comment by mkschreder** [comment]
What is this: 
 static luv_work_ctx_t* luv_check_work_ctx(lua_State* L, int index)
 {
   luv_work_ctx_t* ctx = luaL_checkudata(L, index, "luv_work_ctx");
   luaL_unref(L, LUA_REGISTRYINDEX, ctx->async_cb);
   luaL_unref(L, LUA_REGISTRYINDEX, ctx->async_cb);
 
   return 0;
 }
 
this looks like it will always return zero. I suspect it should return ctx instead.

**Comment by zhaozg** [comment]
where got the code? 
right is here https://github.com/luvit/luv/blob/master/src/work.c#L40

**Comment by creationix** [comment]
I'm back from vacation now, this conversation sounds interesting.

**Comment by zhaozg** [comment]
hi @mkschreder this PR https://github.com/luvit/luv/pull/190 should make you happy

**Comment by mkschreder** [comment]
Very nice. I have not had chance to test all of that yet but it looks
promising.  Thanks.

**Comment by yihuang** [comment]
What if I the event loop running in a worker thread, and I want to use async in the main thread?
I'm using luv in a game, the game thread is the main thread, I want to run network event loop in a separate thread, and I need something like async handler to control the loop in game thread.

**Comment by yihuang** [comment]
Guess I can use pipe?

**Comment by mkschreder** [comment]
I would use a message queue for that. You can not share a lua context
across two threads. Instead you can code a queue in your game engine that
will pass messages to lua code by invoking a lua method in the local lua
context inside the thread that owns it.

**Comment by yihuang** [comment]
@mkschreder I'm using message queue to send requests, but I need a way to notify the event loop thread to pop from that message queue.

**Comment by creationix** [comment]
@yihuang: uv_async?

**Comment by yihuang** [comment]
@creationix Yes, I want to create a uv_async in event loop thread and call it's send method in main thread. I can always create a global uv_async and call with a special engine api, just wonder do you have more elegant solution.
I'm also testing another approach, calling uv.run('nowait') in main thread every frame. How do you think about this approach?

**Comment by creationix** [comment]
I've done the other way where in libuv I have a 60Hz interval that calls my app's main loop but can then use a normal blocking uv.run().

There are ways to more tightly integrate multiple event loops that involve file descriptors, pipes, and smart timeouts.

If I were in C, I would probably just create a global async instance and use it to wake up the main thread.

**Comment by mkschreder** [comment]
You can setup a timeout and repeatedly call a C function from your lua
context that will fetch new events from a thread-safe queue and call your
callbacks that reside in the lua context local to current thread.

**Comment by SinisterRectus** [comment]
After skimming this conversation, and PR #190, I expected that async handles can be passed to threads, yet this code does not work for me:

```lua
local uv = require('luv')

local async = uv.new_async(function(foo)
 print(foo)
end)

local thread = uv.new_thread(function(a)
 require('uv').async_send(a, 'foo')
end, async)

thread:join()
```
```
bad argument #1 to 'async_send' (uv_async expected, got userdata)
```
