### ISSUE TITLE
To find a safe way to pass uv_handle_t in threads

### ISSUE THREAD

**Issue by zhaozg** [luvit/luv#184]
Q: Should we support pass uv_handle_t pass to threads?
A: Because libuv uv_asnyc_t used to pass notify from childs to parent, so simple answer is Yes.
    But without uv_async_t, we have many other solution todo so, simply socket, so It's not deeply need.

Any advice? @creationix  @rphillips 

basic flow
1. when data pass to thread or threadpool by uv.new_thread or uv.queue_work, first check data type, only accept basic lua/luv types, which include (nil, boolean, number, lightuserdata, uv_handle_t), other userdata can't be pass.
2. set ref to user data before real pass.
3. In threadpool, we have chance to clear ref to userdata in work_after_cb call.
4. in thread, when it finish, we clear ref to userdata.

So it's not difficult to do so. but all vu_handle_t should be malloc and userdata just store pointer of data.

ref to : https://github.com/luvit/luv/issues/182

**Comment by creationix** [comment]
I think most the types of handles that can be passed between event loops also have numerical file descriptors that can be passed instead and then re-created in the thread?

How many exceptions to this rule are there?  Are you proposing we handle this internally in the thread code?

**Comment by creationix** [comment]
I'm not sure we can pass handles since they are tied to a single uv_loop_t.
