### ISSUE TITLE
how can I write a native plugin for luv.

### ISSUE THREAD

**Issue by mythay** [luvit/luv#187]
I think luv should export more function to support native plugin, at least
 lua_State* luv_state(uv_loop_t* loop);
// All libuv callbacks will lua_call directly from this root-per-thread state
uv_loop_t* luv_loop(lua_State* L);
are needed, because luv don't use uv_default_loop, so if neither of the function is exported, it is impossiable to write a plugin.

There is Nan in node to make write plugins easily, have you ever planned to implemnt it in luvit?

**Comment by creationix** [comment]
Luv is a C library, I'm not sure what you mean about a native plugin for it.
I assume you mean writing luvit extensions.  There are some instructions at https://github.com/luvit/lit/wiki/Publishing-Compiled-Code

The `luv_state()` and `luv_loop` function are already exported.  I can add them to the luv.h header if that helps any, but it doesn't affect the binary and what's available at all.

As far as Nan, there is no need.  The lua C API is super stable and easy to use already (unlike the V8 API used in node).  Also luajit even has full FFI support in core that's baked into the JIT engine and is super fast.

**Comment by mythay** [comment]
my meaning of plugin is just like node-serial or node-sqlite in node, i must implement some features in async mode or reimplement an exsisting lib in async mode. so i need function both in libuv and luv. there is no problem in linux but not in windows, because i can only use symbols exported explicitly.
so i think the makefile need some modification to export libuv functions in luv.
and luv.h header is redundent (the static declaration cause warnnings )as a lib, it can be divided into two parts.

**Comment by creationix** [comment]
Good point about windows and exports.  It should export the symbols now.  Let me know if this needs anything else.
