### ISSUE TITLE
Build fails on OSX with luarocks

### ISSUE THREAD

**Issue by tbastos** [luvit/luv#198]
Is anyone using `luv` on OSX? Via luarocks?

``` sh
[  3%] Building C object CMakeFiles/uv.dir/deps/libuv/src/fs-poll.c.o
In file included from /tmp/luarocks_luarocks-source-luv-1.7.4-5-4785/luv-1.7.4-5/deps/libuv/src/fs-poll.c:22:
In file included from /tmp/luarocks_luarocks-source-luv-1.7.4-5-4785/luv-1.7.4-5/deps/libuv/include/uv.h:48:
/tmp/luarocks_luarocks-source-luv-1.7.4-5-4785/luv-1.7.4-5/deps/libuv/include/uv-errno.h:25:10: fatal error:
      'errno.h' file not found
#include <errno.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/uv.dir/deps/libuv/src/fs-poll.c.o] Error 1
make[1]: *** [CMakeFiles/uv.dir/all] Error 2
make: *** [all] Error 2
```

This other project installs without problems via luarocks: https://github.com/moteus/lua-lluv

**Comment by creationix** [comment]
I published a new version a couple days ago, it works for me on a fresh OSX machine.

**Comment by tbastos** [comment]
@creationix I finally found the problem:
```sh
luarocks install luv # fails like in the OP
CC=gcc luarocks install luv # works!
```
For some reason the luarocks/CMake build fails with the default environment on OSX, but works if I set the env var `CC=gcc` (which is set by default on Travis, for some reason).

Are you on OSX 10.11? Do you set `CC=gcc`? Thanks

**Comment by tbastos** [comment]
Found the real culprit... some Xcode update must have corrupted my framework files. All my projects were building ok but luv was failing randomly. After deleting Xcode and re-runing `xcode-select --install` luv now installs correctly via luarocks even without `CC=gcc`. Sorry and thank you Apple....

**Comment by creationix** [comment]
Sorry for the trouble, glad you figured it out.
