### ISSUE TITLE
Function fs_scandir_next creates tables unnecessarily

### ISSUE THREAD

**Issue by tbastos** [luvit/luv#201]
I think `fs_scandir_next` is being unnecessarily wasteful here: https://github.com/luvit/luv/blob/master/src/fs.c#L406-L436

Instead of creating a table at each call it could simply return 2 values (name and type). For programs that scan lots of big dirs, this is going to be much faster, and more importantly won't create a lot of garbage and put a lot of pressure on the GC.

The resulting code is also simpler to use. A table only adds complexity here, IMHO.

**Comment by creationix** [comment]
Good idea.  This will be a breaking change to the API, but probably worth it.

**Comment by creationix** [comment]
@tbastos could you send a PR, my dev machine is currently out of order.  If not, I'll get to it some time.

**Comment by tbastos** [comment]
Cool I'll work on it... sorry for the delay.
