### ISSUE TITLE
Luarocks-based install failing on Windows

### ISSUE THREAD

**Issue by tbastos** [luvit/luv#202]
Hey,

`luarocks install luv` is working fine for me on OSX and Linux, but not on Windows.

On Windows `msvcbuild.bat` works, but Luarocks fails due to crazy CMake errors. After some digging, I found this line, in the rockspec file, to be the culprit: `PREFIX="$(PREFIX)"`. If I remove this line CMake finds all MSVC tools correctly, but the build still fails because it's still trying to use the bundled Luajit instead of the Lua I'm using with Luarocks. At this point I gave up.

Do you consider "officially supporting" luarocks anytime soon (ideally by adding "luarocks install luv" to Travis and AppVeyor)?

Thanks

**Comment by creationix** [comment]
Yes, I want to officially support luarocks, I'm just not experienced with it.  Why does PREFIX break windows, I'm just forwarding on some environment variables I thought.

**Comment by tbastos** [comment]
It seems `${PREFIX}` affects how CMake searches for compilers (at least MSVC). As far as I could tell PREFIX is not being used in CMake anyways.

I fixed some things in CMakeLists.txt and now `luarocks install luv` works on Windows. I'll send a pull request soon.

**Comment by creationix** [comment]
Thanks

**Comment by tbastos** [comment]
Fixed by pull request #209
