### ISSUE TITLE
Process spawn() stdio can not specify UV_IGNORE with sparse table

### ISSUE THREAD

**Issue by brimworks** [luvit/luv#204]
The stdio option is handled as such:

```
options.stdio_count = len = lua_rawlen(L, -1);
```

...and the UV_IGNORE is specified as such:

```
else if (lua_type(L, -1) == LUA_TNIL) {
```

Due to how Lua handles sparse tables, setting STDIN (table element 1) to nil may trigger `lua_rawlen` to be set to 0 and thus making it impossible to specify STDOUT/STDERR when STDIN is set to nil. I've got this workaround that seems to work:

```
local function hack_stdio(stdio)
    local result
    if nil ~= stdio[3] then
        return {stdio[1], stdio[2], stdio[3]}
    end
    if nil ~= stdio[2] then
        return {stdio[1], stdio[2]}
    end
    if nil ~= stdio[1] then
        return {stdio[1]}
    end
    return {}
end
```

...but it would be much better if we could specify a "null" value that represents a file descriptor that we want to be set to UV_IGNORE. As a side-note, for interoperability, I've found it is best to check if a userdata has the __name metatable field set to "null" to determine if an object is null. I've found this gives the maximum interoperability.

See https://github.com/mpx/lua-cjson/issues/11#issuecomment-137562575

**Comment by brimworks** [comment]
BTW, I'm willing to code-up a pull request that works something like this (not tested):

```
...
else if (lua_type(L, -1) == LUA_TUSERDATA) {
    int processed = 0;
    if (lua_getmetatable(L, -1)) {
        lua_pushliteral(L, "__name");
        lua_rawget(L, -2);
        if (lua_isstring(L, -1) && strcmp("null", lua_tostring(L, -1)) == 0) {
            options.stdio[i].flags = UV_IGNORE;
            processed = 1;
        }
    }
    if ( ! processed ) {
        ...do the normal stream stuff.
    }
}
```

**Comment by creationix** [comment]
How about we just set a minimum to len to be 3 so that nil doesn't get in the way?

**Comment by brimworks** [comment]
The libuv manual seems to indicate that you can use file descriptors > 3:

```
uv_process_options_t.stdio
The stdio field points to an array of uv_stdio_container_t structs that describe the file descriptors that will be made available to the child process. The convention is that stdio[0] points to stdin, fd 1 is used for stdout, and fd 2 is stderr.

Note On Windows file descriptors greater than 2 are available to the child process only if the child processes uses the MSVCRT runtime.
```

http://docs.libuv.org/en/latest/process.html

...I don't personally use this feature (yet), but it would be nice if we could maintain that flexibility.

Thanks,
-Brian

**Comment by creationix** [comment]
You'll still be able to use descriptors above 2, I'm just suggesting to check for first 3 in all cases.

**Comment by brimworks** [comment]
How would this work if `stdio[1] = nil` and `stdio[4] = 1`? I do like the idea of always checking the first 3 as long as index 3+ still work properly. Is your thought to do a for loop until index 3 or more contains a nil value? If so, it just means this has to happen twice, once to allocate the right sized array, then a second time to populate the array.

Do you want me to implement this and post a pull request?

**Comment by creationix** [comment]
The logic can be simple, instead of using rawlength, just use a normal loop.  Keep looping as long as the index is less than or equal to 3 or contains a non-nil value.

This means we won't support 4 nils followed by a value, but that's fine I think.

**Comment by brimworks** [comment]
At last I've gotten around to proposing a fix:

https://github.com/luvit/luv/pull/235

This approach allows non-STDIO file descriptors to exist in a sparse array.

Thanks,
-Brian
