### ISSUE TITLE
New release with bindings for libuv 1.8.0

### ISSUE THREAD

**Issue by joerg-krause** [luvit/luv#205]
Can you submit a new release with the bindings for libuv 1.8.0, please?

And don't forget to update the version string in CMakeLists.txt: https://github.com/luvit/luv/blob/master/CMakeLists.txt#L6-L8 :smile:

Many thanks!

**Comment by creationix** [comment]
Thanks for the reminder.  Published 1.8.0-0 to github and luarocks and updated the CMAKELists file.
