### ISSUE TITLE
Memory leak in luv_fs_read?

### ISSUE THREAD

**Issue by tbastos** [luvit/luv#208]
Am I missing something, or is this `malloc` leaking?

https://github.com/luvit/luv/blob/master/src/fs.c#L324

Couldn't figure out where that memory is freed.

Thanks

**Comment by rphillips** [comment]
It should get cleaned up with luv_cleanup_req. The malloc needs to be able to span the time it takes for the callback to happen or an error with the call.

https://github.com/luvit/luv/blob/master/src/fs.c#L243-LL297

**Comment by tbastos** [comment]
Ahh thanks! Sorry for the noise!
