### ISSUE TITLE
Use existing libuv when installing from luarocks

### ISSUE THREAD

**Issue by tarruda** [luvit/luv#222]
I'd like to use an existing libuv build when installing luv with `luarocks install luv`. Is such thing possible?

If not, is it possible to lower the version requirements of `uv.cmake`? I currently cannot install luv on travis since it requires cmake 2.8.9(travis has 2.8.7).

**Comment by creationix** [comment]
I'm not sure about either of those, but you can get newer cmake on travis easy enough https://github.com/luvit/luvi/blob/a3ec57fe2e895a562645b9eac4aed79a06f9d49b/.travis.yml#L4-L9

**Comment by tarruda** [comment]
@creationix thanks, that solves my issue
