### ISSUE TITLE
Can't create 32-bit build

### ISSUE THREAD

**Issue by tarruda** [luvit/luv#223]
neovim build system downloads a bunch of dependencies, including a number of luarocks modules required during the build process such as lpeg and a client library based on libuv that now uses luv as the backend(instead of a simple libuv binding module).

The problem is that luv.so is always built as a 64-bit library, even when doing 32-bit builds with both CFLAGS and LDFLAGS set to -m32. Normally we can force luarocks to install 32-bit modules by passing `gcc -m32` as `CC` and `LD`, but this seems to be failing with luv

I also tried to build from luv source tree:

```
mkdir build
cd build
CC='gcc -m32' LD='gcc -m32' cmake ..
```

which fails with:

```
-- The C compiler identification is GNU 5.2.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Looking for dlopen
-- Looking for dlopen - not found
CMake Error at deps/luajit.cmake:84 (MESSAGE):
  Cannot compile a useful lua.

  Function dlopen() seems not to be supported on your platform.

  Apparently you are not on a Windows platform as well.

  So lua has no way to deal with shared libraries!
Call Stack (most recent call first):
  CMakeLists.txt:106 (include)
```

**Comment by creationix** [comment]
@rphillips do you have any insight here?

**Comment by tarruda** [comment]
It seems the problem is in the build scripts under the "deps" directory, I managed to create a 32-bit build by manually specifying the location of 32-bit builds of libuv and luajit:

```sh
CFLAGS="-m32 -I${DEPS32_PREFIX}/include/luajit-2.0 -I${DEPS32_PREFIX}/include" LDFLAGS="-m32 -L{$DEPS32_PREFIX}/lib" WITH_SHARED_LIBUV=ON LUA_BUILD_TYPE=System make
```

Still, I think something should be done about the luarocks build, as it ignores the flags passed to it.
