### ISSUE TITLE
luv_check_callback NULL dereference

### ISSUE THREAD

**Issue by justinmk** [luvit/luv#234]
In https://github.com/neovim/neovim/pull/4743#issuecomment-218944511 we ran into a situation where `luv_check_callback` gets a null `data` argument. 

I notice that most of the `luv_check_*` functions (`luv_check_process`, `luv_check_poll`, `luv_check_idle`, `luv_check_signal`, ...) in luv check for `handle->data != NULL`. But `luv_check_stream` and `luv_check_handle` do not.

**Comment by creationix** [comment]
Thanks, I'll see if I patch this.

**Comment by creationix** [comment]
I added a quick sanity check, you'll probably get a different error now in whatever was triggering the segfault in neovim.

I'd still like to have a more robust type checking system, but this should at least prevent null deferences for the `luv_handle_t`.

**Comment by justinmk** [comment]
Thanks!
