### ISSUE TITLE
Unable to complete tests (stuck at basic tcp server and client test)

### ISSUE THREAD

**Issue by jpleau** [luvit/luv#236]
Hi.

I am not able to fully run tests on my system (debian sid/unstable). I always get stuck on "CATCH SIG":
```
ok 57 process - process stdio
  Sending child SIGINT
  "exit"	{ signal = 0, code = 7, pid = 25718 }
ok 58 signal - Catch SIGINT
  { server = uv_tcp_t: 0x01f2c500, address = { ip = "0.0.0.0", family = "inet", port = 52729 } }
  { client = uv_tcp_t: 0x01f2af50 }
```

Nothing happens after that.

I am however able to run the tests in a clean debian sid virtual machine. Could something running on my system be the cause of this?

**Comment by creationix** [comment]
I'm sorry you're having this issue.  I can't look into it right now.  If you do figure out the root cause, please update us.

**Comment by jpleau** [comment]
Digged a bit further, the test that is hanging is in test-tcp.lua, more precisely the first one called "basic tcp server and client".

Removing that test everything works fine, disabling all the others and I get the same hanging

I think it is because I have disabled IPv6 on my machine, ::1 can't resolve to anything.

Will test and update :)

**Comment by jpleau** [comment]
Yup. Enabling ipv6 fixes everything. Sorry for the noise :)

**Comment by creationix** [comment]
No problem, thanks for figuring it out.
