### ISSUE TITLE
bug in luv_new_tcp

### ISSUE THREAD

**Issue by strrchr** [luvit/luv#242]
```
static int luv_new_tcp(lua_State* L) {
  lua_settop(L, 1); // FIXED: or lua_isnoneornil(L, 1) will test the userdata!
  uv_tcp_t* handle = (uv_tcp_t*)luv_newuserdata(L, sizeof(*handle));
  int ret;
  if (lua_isnoneornil(L, 1)) {
    ret = uv_tcp_init(luv_loop(L), handle);
  }
```

**Comment by creationix** [comment]
Thanks.  I wonder what kind of undefined behavior we've been causing.  I guess if the userdata always converts to 0 as an integer it was at least harmless.

**Comment by creationix** [comment]
How did you find this bug?  Was it causing bad behavior or did you just see it reviewing the code?  I'd like to know what the impact was.

**Comment by strrchr** [comment]
I found this bug occasionally when debugging a mysterious crash.
But the crash is not related to luv_new_tcp. It is bug in LuaJIT. After I upgrade to new LuaJIT version, the crash disappear.
I think the bug in luv_new_tcp has little impact, it only causes no flags is passed to uv_tcp_init_ex(uv_loop_t* loop, uv_tcp_t* handle, unsigned int flags).

**Comment by creationix** [comment]
Thanks.  I just made a new luvi release yesterday that uses the latest luajit 2.1 as well as this fix.  Thanks for reporting it even it probably wasn't causing any trouble.
