### ISSUE TITLE
Is luv support pipe server and pipe client ?

### ISSUE THREAD

**Issue by uudiin** [luvit/luv#253]
The uv_pipe_listen, uv_pipe_accept, uv_pipe_write and uv_pipe_read_start are not implemented.

**Comment by creationix** [comment]
Are those new API functions in libuv.  I thought I had gotten all the pipe functions back when I was writing the bindings.

It shouldn't be hard to add them.  I'll bet they work a lot like the TCP variants.

**Comment by uudiin** [comment]
I'm sorry, It works in Stream, it's my fault.
Thank you.

**Comment by creationix** [comment]
Oh yeah, that's why they both "inherit" from stream. :)

(I'm very tired today and not thinking very clearly)
