### ISSUE TITLE
cancel causes future SEGV

### ISSUE THREAD

**Issue by brimworks** [luvit/luv#257]
When I try to run `uv.cancel(req)`, when the callback associated with `req` is ran a segmentation fault occurs.

Per the documentation of uv_cancel():

http://docs.libuv.org/en/v1.x/request.html

...the request data should not be deallocated until the callback is ran, and all callbacks need to check for the canceled state.

My branch is pretty old, but looking at the latest code on master, it appears that request data deallocation is still happening when cancel is called:

https://github.com/luvit/luv/blob/master/src/req.c#L48

This is my fix, I can extract this into a pull request against master if desired:

https://github.com/brimworks/luv/commit/7425d8bea5278392fa1bf15bd68b2abe33726857

This seems to fix the SEGV for me and the request does actually get canceled.

Thanks,
-Brian

**Comment by creationix** [comment]
That's awesome.  cancel was the one part of libuv I never figured out.  It wasn't a priority since nobody seemed to use it.

Yes, a PR would be welcome.

**Comment by brimworks** [comment]
PR sent... as mentioned in the PR this is probably incomplete, but at least we don't get a SEGV :).

https://github.com/luvit/luv/pull/258
