### ISSUE TITLE
Share mutex?

### ISSUE THREAD

**Issue by Nathan1852** [luvit/luv#274]
The readme states that 'You can't share uv handles between states/loops.'

Is that also true for uv_mutex_t 'handles'?

I just want to make sure, since I'm writing a simple channel lib for sharing data between threads, and it sometimes needs a uv_mutex_t

**Comment by creationix** [comment]
I think this question is better asked at the libuv people.  I don't know the constraints there.

**Comment by Nathan1852** [comment]
Will do. Thanks
