### ISSUE TITLE
Please update the Luarocks package

### ISSUE THREAD

**Issue by slact** [luvit/luv#275]
The package on Luarocks.org hasn't been updated in over a year and is missing some critical fixes. Please release an up-to-date version so that my own luarocks don't have to include and build luv "by hand".

**Comment by justinmk** [comment]
@creationix Any plans for a release?

**Comment by creationix** [comment]
I'd love to.  I've just been crazy busy.  Ping me next week and I'll see if I can get a new release of everything out.

**Comment by cliffordjefferies** [comment]
Having an issue building - 
sudo luarocks install luv
Installing https://rocks.moonscript.org/luv-1.22.0-0.src.rock...
Using https://rocks.moonscript.org/luv-1.22.0-0.src.rock... switching to 'build' mode
-- The C compiler identification is GNU 5.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Lua: using information from luarocks
-- LUA_LIBDIR: /usr/local/lib
-- LUA_INCDIR: /usr/include/lua5.1
-- LUA: /usr/bin/lua5.1
-- Lua library: LUA_LIBRARIES-NOTFOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_luv-1.22.0-0-1939/luv-1.22.0-0
Scanning dependencies of target uv
[  1%] Building C object deps/libuv/CMakeFiles/uv.dir/src/fs-poll.c.o
[  3%] Building C object deps/libuv/CMakeFiles/uv.dir/src/inet.c.o
[  4%] Building C object deps/libuv/CMakeFiles/uv.dir/src/threadpool.c.o
[  6%] Building C object deps/libuv/CMakeFiles/uv.dir/src/timer.c.o
[  7%] Building C object deps/libuv/CMakeFiles/uv.dir/src/uv-common.c.o
[  9%] Building C object deps/libuv/CMakeFiles/uv.dir/src/uv-data-getter-setters.c.o
[ 10%] Building C object deps/libuv/CMakeFiles/uv.dir/src/version.c.o
[ 12%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/async.c.o
[ 13%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/core.c.o
[ 15%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/dl.c.o
[ 16%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/fs.c.o
[ 18%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/getaddrinfo.c.o
[ 19%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/getnameinfo.c.o
[ 21%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/loop-watcher.c.o
[ 22%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/loop.c.o
[ 24%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/pipe.c.o
[ 25%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/poll.c.o
[ 27%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/process.c.o
[ 28%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/signal.c.o
[ 30%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/stream.c.o
[ 31%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/tcp.c.o
[ 33%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/thread.c.o
[ 34%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/tty.c.o
[ 36%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/udp.c.o
[ 37%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/proctitle.c.o
[ 39%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/linux-core.c.o
[ 40%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/linux-inotify.c.o
[ 42%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/linux-syscalls.c.o
[ 43%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/procfs-exepath.c.o
[ 45%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/sysinfo-loadavg.c.o
[ 46%] Building C object deps/libuv/CMakeFiles/uv.dir/src/unix/sysinfo-memory.c.o
[ 48%] Linking C shared library libuv.so
[ 48%] Built target uv
Scanning dependencies of target luv
[ 50%] Building C object CMakeFiles/luv.dir/src/luv.c.o
In file included from /tmp/luarocks_luv-1.22.0-0-1939/luv-1.22.0-0/src/luv.c:18:0:
/tmp/luarocks_luv-1.22.0-0-1939/luv-1.22.0-0/src/luv.h:54:30: fatal error: c-api/compat-5.3.h: No such file or directory
compilation terminated.
CMakeFiles/luv.dir/build.make:62: recipe for target 'CMakeFiles/luv.dir/src/luv.c.o' failed
make[2]: *** [CMakeFiles/luv.dir/src/luv.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/luv.dir/all' failed
make[1]: *** [CMakeFiles/luv.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by squeek502** [comment]
@creationix looks like `deps/lua-compat-5.3` is not being included in the luarocks release `.tar.gz`. [This line of the Makefile should be updated](https://github.com/luvit/luv/blob/master/Makefile#L58).

Would also be nice to get a new Luarocks build anyway to include the build fixes in #297

**Comment by creationix** [comment]
> I can work on that if it sounds good to you.

That would great if you have the time.

**Comment by squeek502** [comment]
> That would great if you have the time.

Created a PR: #304

**Comment by teto** [comment]
Could you please upload a src.rock( https://github.com/luarocks/luarocks/wiki/Creating-a-rock#pack-command)  on luarocks too ? I package luv for the distrib and at the moment, having src.rock is a lot better (working on automating packaging from rockspec but not quite there yet).

**Comment by squeek502** [comment]
Should be taken care of regularly now.
