### ISSUE TITLE
Cannot access self from callbacks

### ISSUE THREAD

**Issue by tversteeg** [luvit/luv#278]
I saw that in a [commit](https://github.com/luvit/luv/commit/de47457b854be241f856decaf4c2b4f311283354) many years ago the `self` argument to callbacks was removed. How can `self` be accessed from a callback now?

For example I want to do something like this:

```lua
local object = {}
object.__index = object

-- Constructor
function object:new()
	local obj = {}
	setmetatable(obj, object)

	obj.client = nil
	obj.client_status = ""

	return obj
end

function object:connect(ip, port)
	-- Instantiate the object
	self.client = uv.new_tcp()

	-- Try to connect to the ip and address
	self.client:connect(ip, port, self.connection_callback)
end

function object:connection_callback(err)
	-- Close the client and print the message if there's an error
	if err then
		self.client_status = "Error: " .. err
		self.client = nil
		print(err)
	end

	self.client_status = "Connected"
end
```

It looks like the `err` argument is written over `self` in `connection_callback`...

**Comment by imzyxwvu** [comment]
Try using anonymous function to create a closure as a callback:

    self.client:connect(ip, port, function() ... end)

**Comment by tversteeg** [comment]
If I try to access `self` from the closure it's `nil`.

**Comment by squeek502** [comment]
To be more specific, this should work:

```
self.client:connect(ip, port, function(...) self:connection_callback(...) end)
```

**Comment by tversteeg** [comment]
Yes that's it! Thanks a lot, sorry for opening an issue for this..
