### ISSUE TITLE
Favor `make amalg` in LuaJIT build process

### ISSUE THREAD

**Issue by mnemnion** [luvit/luv#288]
Hi,

LuaJIT can be compiled as an amalgamation, allowing the  C compiler to perform whole-program 
optimizations.  The resulting binary is more compact, and faster. 

I'd like to propose that this be the default build progress. It takes 400MB, according to the helpful popup the build will display if `make amalg` is chosen. So it would also be polite to provide a -D level
flag to use the default build process.

Apologies for not submitting a patch, I'm new to cmake and the learning curve is steep.  It's much easier for my purposes to simply build the binary myself. 

Thank you for such an excellent library! I hope to make good use of it.

**Comment by zhaozg** [comment]
after https://github.com/luvit/luv/commit/201c17e81ce57a3566b99c66077384ebe0d903b5,
default `make` will do luajit amalg build, and `make WITHOUT_AMALG=YES` will disable luajit amalg build.

**Comment by creationix** [comment]
Thanks @zhaozg.  I plan on doing a new release of everything (luv luarocks, luv github, luvi github, luvi binaries, lit, and luvit) next week if I'm able to find time.

**Comment by zhaozg** [comment]
@creationix, Before that, I will change and merge https://github.com/neovim/neovim/blob/master/third-party/patches/luv-Add-missing-definitions-for-MinGW.patch

**Comment by creationix** [comment]
About finding time, It seems my life is ever busy.
