### ISSUE TITLE
CI fails / build errors

### ISSUE THREAD

**Issue by squeek502** [luvit/luv#297]
Will try to fix this stuff soon, just wanted to write it down for now.

1. The static build links against the shared libuv library (`uv`) instead of the static one (`uv_a`).
2. Libuv does its full build/install instead of just compiling the necessary library component (I believe this can be fixed by adding EXCLUDE_FROM_ALL to the add_subdirectory call)
3. Windows fails to link (`error LNK2019: unresolved external symbol __imp_close referenced in function uv_tty_close`) due to mismatched `/MD` and `/MT` flags between libuv/luv. This is likely caused by the `/MT` replacement ([`string(REPLACE "/MD" "/MT" ${CompilerFlag} "${${CompilerFlag}}")`](https://github.com/luvit/luv/blob/master/CMakeLists.txt#L172)) not affecting the libuv subdirectory compiler flags (so libuv uses `/MD` while luv uses `/MT`).

I'm unsure about the reasoning behind the 3rd point. Any reason why `/MT` should be used?

**Comment by creationix** [comment]
I think I fixed the first two, not sure how to tackle the 3rd.

**Comment by creationix** [comment]
Hmm, maybe not.  Maybe we need to add `libuv.a` as a target somewhere.  It all build just fine on my computer, but I've got the arch version of node.js which includes a system version of libuv.

**Comment by creationix** [comment]
On my system, I get the following when building:

```
[ 96%] Linking C static library libuv_a.a
make[3]: Leaving directory '/home/tcaswell/Code/luv/build'
[ 96%] Built target uv_a
make[3]: Entering directory '/home/tcaswell/Code/luv/build'
Scanning dependencies of target luv
make[3]: Leaving directory '/home/tcaswell/Code/luv/build'
make[3]: Entering directory '/home/tcaswell/Code/luv/build'
[ 98%] Building C object CMakeFiles/luv.dir/src/luv.c.o
[100%] Linking C shared module luv.so
```

**Comment by squeek502** [comment]
That looks right to me for `WITH_SHARED_LIBUV=OFF`?

**Comment by creationix** [comment]
This is supposed to be the same right? https://travis-ci.org/luvit/luv/jobs/411928172#L1388

**Comment by squeek502** [comment]
Probably not, might need to be `-luv_a` to maintain the same functionality. In the previous `uv.cmake`, libuv was [always built as static](https://github.com/luvit/luv/blob/8e5b78c32b7d859b05bdd7d81c523390a99087c1/deps/uv.cmake#L193), but in the new Libuv subproject, the static library is `uv_a`.

However, there's something else going wrong there as well: the location of the built libuv library has moved due to the subproject, so `build/libuv.a` does not exist in [this step](https://travis-ci.org/luvit/luv/jobs/411928172#L1377) (it's now at `build/deps/libuv/libuv_a.a` I believe).

So, both could be fixed at the same time potentially by fixing the `cp` command but also renaming `libuv_a.a` to `libuv.a` during the copy, thus making `-luv` work again.
