### ISSUE TITLE
Release 1.25.0

### ISSUE THREAD

**Issue by joerg-krause** [luvit/luv#315]
Can you submit a new release with the bindings for libuv 1.25.0, please?

**Comment by squeek502** [comment]
For anyone with push access (@rphillips @creationix @zhaozg), since https://github.com/luvit/luv/pull/304 all you should need to do is push a tag with the Luarocks version number (i.e. `1.25.0-0`) and everything else should be automatic.

**Comment by creationix** [comment]
I pushed a tag, here's hoping it works.

**Comment by squeek502** [comment]
It worked :tada: 
```
> luarocks install luv
luv 1.25.0-0 is now installed
Removing luv 1.22.0-1...
Removal successful.
```

**Comment by joerg-krause** [comment]
Thanks!

**Comment by creationix** [comment]
Sweetness
