### ISSUE TITLE
Add static building support

### ISSUE THREAD

**Issue by TSnake41** [luvit/luv#319]
Adding static building support for luv (building to `libluv.a`) to embed luv into a non-lua program (luvi maybe ?).

So, the idea is to build to a libluv.a that provides the "luaopen_luv" function, it stills needs lua headers to build (with the right version).

**Comment by squeek502** [comment]
This is what the CMake option `BUILD_MODULE=OFF` does. [See here for how luvi builds static luv](https://github.com/luvit/luvi/blob/master/CMakeLists.txt#L96-L107).

**Comment by squeek502** [comment]
See also https://github.com/luvit/luv#build-as-static-library
