### ISSUE TITLE
Sometimes when I try running a script with luvit it doesn't work

### ISSUE THREAD

**Issue by karimrir1** [luvit/luv#324]

**Comment by squeek502** [comment]
Need more info.

What's the script? What error are you getting?

**Comment by karimrir1** [comment]
I'm trying to run a discord bot but with lua, So I had to use discordia to code it and I only can run it 2 times then it won't run again, There's was no error in the script or even the console.

**Comment by SinisterRectus** [comment]
You're in the wrong place. Visit https//discord.gg/discord-api for support.
