### ISSUE TITLE
luajit 2.1 is not found (Alpine Linux): Could NOT find LUAJIT

### ISSUE THREAD

**Issue by blueyed** [luvit/luv#342]
Alpine Linux has luajit 2.1 (https://pkgs.alpinelinux.org/package/edge/main/x86_64/luajit-dev), which is not detected:

```console
% cmake build -DLUA_BUILD_TYPE=System
-- Could NOT find LUAJIT (missing: LUAJIT_INCLUDE_DIR)
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luv/build
```

The following patch fixes it, but there is likely a better way in general:

```diff
diff --git a/cmake/Modules/FindLuaJIT.cmake b/cmake/Modules/FindLuaJIT.cmake
index fedcc32..0d0786e 100644
--- a/cmake/Modules/FindLuaJIT.cmake
+++ b/cmake/Modules/FindLuaJIT.cmake
@@ -23,7 +23,7 @@
 #  LUA_VERSION_MINOR  - the minor version of Lua
 #  LUA_VERSION_PATCH  - the patch version of Lua

-FIND_PATH(LUAJIT_INCLUDE_DIR NAMES lua.h PATH_SUFFIXES luajit-2.0)
+FIND_PATH(LUAJIT_INCLUDE_DIR NAMES lua.h PATH_SUFFIXES luajit-2.0 luajit-2.1)
 FIND_LIBRARY(LUAJIT_LIBRARIES NAMES luajit-5.1 luajit)

 if (LUAJIT_INCLUDE_DIR AND EXISTS "${LUAJIT_INCLUDE_DIR}/lua.h")
```

E.g. Neovim used pkg-config, which should be more robust: https://github.com/neovim/neovim/blob/master/cmake/FindLuaJit.cmake (but also has only luajit-2.0 in PATH_SUFFIXES there currently still).

**Comment by squeek502** [comment]
That patch looks like a good solution for now. Want to make a PR with it?

**Comment by blueyed** [comment]
Ok: https://github.com/luvit/luv/pull/343

I expect some followup maybe in this regard, since I plan to revisit / look into Neovim's handling of it.

So either do not rush with merging it, or expect some followup later.
