### ISSUE TITLE
Provide package config

### ISSUE THREAD

**Issue by blueyed** [luvit/luv#354]
It would be helpful if luv would ship a pkg-config file, which would allow to check for required versions etc.

See https://github.com/libuv/libuv/blob/master/libuv.pc.in (and https://github.com/libuv/libuv/blob/988091dada1c9cbe4d4b88b1844ac6f2ad99d0ef/CMakeLists.txt#L386) for how libuv does it.

**Comment by teto** [comment]
yes that would be super useful for packing on systems like nixos with non standard paths.

**Comment by zhaozg** [comment]
ok, let me try

**Comment by zhaozg** [comment]
Please look at here https://github.com/luvit/luv/pull/355

**Comment by zhaozg** [comment]
run `make BUILD_MODULE=0 install`  get 
```
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libluv.a
-- Installing: /usr/local/lib/pkgconfig/libluv.pc
-- Up-to-date: /usr/local/include/luv/luv.h
-- Up-to-date: /usr/local/include/luv/util.h
-- Up-to-date: /usr/local/include/luv/lhandle.h
-- Up-to-date: /usr/local/include/luv/lreq.h
```
