### ISSUE TITLE
Memory leak (loop was never GCed)

### ISSUE THREAD

**Issue by vanc** [luvit/luv#379]
Compiled luv.so with CLANG's address sanitizer, and run the unit tests, and found lots of leaks.

Troubleshooted a bit and found that the luv.c:loop_gc() was never triggered.

The issue seems started from revision db55f6bd.

    lua_pushstring(L, "_loop");
    loop = (uv_loop_t*)lua_newuserdata(L, sizeof(*loop));
    lua_rawset(L, -3);  // ref to loop, avoid __gc early

If remove the pushstring and rawset, loop_gc would be invoked too early, just as the comment says. However, with that, it was never called.

**Comment by squeek502** [comment]
Found the problem: `uv_loop.meta` is being set on the table returned from require (i.e. `getmetatable(require('luv')).__gc`), not the loop userdata. Will create a PR with the fix in a second.

Thanks for finding a reporting this @vanc ! If feasible, we should definitely try to include checks like this into our CI.
