### ISSUE TITLE
Early initialization of userdata interferes with expected arguments

### ISSUE THREAD

**Issue by SinisterRectus** [luvit/luv#390]
This is a good one...

Code:
```lua
local thread = uv.new_thread()
```
Output:
```
bad argument #1 to 'new_thread' (function expected, got userdata)
```
The error message should say "got no value", but....
```c
static int luv_new_thread(lua_State* L) {
  int ret;
  size_t len;
  const char* buff;
  luv_thread_t* thread;
  int cbidx = 1;
  ...
  thread = (luv_thread_t*)lua_newuserdata(L, sizeof(*thread));
  memset(thread, 0, sizeof(*thread));
  luaL_getmetatable(L, "uv_thread");
  lua_setmetatable(L, -2);
  ...
  buff = luv_thread_dumped(L, cbidx, &len);
  ...
}
```
The call to `lua_newuserdata` pushes the `luv_thread_t` userdata to the stack in the position where the function is expected by `luv_thread_dumped`.

Obviously just pass the correct arguments to avoid the issue, but I wonder if creating the userdata early is incorrect here, or in other `uv.new_foo` calls.

**Comment by squeek502** [comment]
Should definitely be handling this better. Seems like a bug.

**Comment by zhaozg** [comment]
I am far away with my computer, handle it yourself or wait me some days.
