### ISSUE TITLE
"leaks - fs-write" test fails on ppc64/1.30.1

### ISSUE THREAD

**Issue by jamessan** [luvit/luv#429]
The Debian [ppc64 build](https://buildd.debian.org/status/fetch.php?pkg=lua-luv&arch=ppc64&ver=1.30.1-1-1&stamp=1572349429&raw=0) failed with the below test failure:

```
  480	3604480
  960	3604480
  1440	3604480
  1920	3604480
  2400	6422528
  2880	6422528
  3360	6422528
  3840	6422528
  { after = 6422528, before = 3604480 }
  ./tests/test-leaks.lua:24: assertion failed!
  stack traceback:
  	[C]: in function 'assert'
  	./tests/test-leaks.lua:24: in function 'bench'
  	./tests/test-leaks.lua:28: in function 'fn'
  	./lib/tap.lua:53: in function <./lib/tap.lua:42>
  	[C]: in function 'xpcall'
  	./lib/tap.lua:42: in function 'run'
  	./lib/tap.lua:136: in function 'tap'
  	tests/run.lua:35: in main chunk
not ok 20 leaks - fs-write
```

This was with the app shim (statically linked against luv) I've previously mentioned. The test passed when using lua to directly run the tests and with a dynamically linked app.  Maybe it's just flaky?

**Comment by squeek502** [comment]
These leak tests can be flaky, since they are checking `uv.resident_set_memory()` which counts more than just the memory used by Lua. Some of them fail when compiling with ASAN as well due to the memory overhead of ASAN at runtime. Could be something similar happening here.

These tests might no longer be necessary after #395 which would be a better way of ensuring we're free of leaks.

**Comment by jamessan** [comment]
> These tests might no longer be necessary after #395 which would be a better way of ensuring we're free of leaks.

Ok.  Feel free to close this and #428 then, if these are going to go away.  I've disabled the tests in Debian for now.

**Comment by squeek502** [comment]
Will close them once #432 is merged (which removes `test-leaks.lua` from the test runner).

Also note that you might want to wait a bit before releasing a new Debian version if you want something more stable. We're somewhat in the middle of making some important changes to get Luv to a stable point again, but the next few releases should be much better (see things like #433, #397, #399, #400).
