### ISSUE TITLE
[riscv64] ./tests/test-tcp.lua:175: attempt to call a nil value (field 'tcp_close_reset')

### ISSUE THREAD

**Issue by davidlt** [luvit/luv#439]
Hi,

I am trying to build lua-luv-1.32.0.0-0.fc32.src.rpm in Fedora/RISCV, but seems that at least one test is failing:
```
ok 71 tcp - tcp invalid ip address
  { server = uv_tcp_t: 0x2aaaace180, address = { family = "inet", ip = "127.0.0.1", port = 34659 } }
  { socket = uv_tcp_t: 0x2aaab05680, req = uv_write_t: 0x2aaab1ab98 }
  "client onwrite"	uv_tcp_t: 0x2aaab05680	nil
  "server read"	{ data = "Hello" }
  "client read"	{ data = "Hello" }
BUILDSTDERR: Uncaught Error: ./tests/test-tcp.lua:175: attempt to call a nil value (field 'tcp_close_reset')
BUILDSTDERR: stack traceback:
BUILDSTDERR: 	./tests/test-tcp.lua:175: in upvalue 'fn'
BUILDSTDERR: 	./lib/tap.lua:48: in function <./lib/tap.lua:46>
BUILDSTDERR: 	[C]: in function 'luv.run'
BUILDSTDERR: 	./lib/tap.lua:55: in function <./lib/tap.lua:42>
BUILDSTDERR: 	[C]: in function 'xpcall'
BUILDSTDERR: 	./lib/tap.lua:42: in upvalue 'run'
BUILDSTDERR: 	./lib/tap.lua:138: in function 'lib/tap'
BUILDSTDERR: 	tests/run.lua:23: in main chunk
BUILDSTDERR: 	[C]: in ?
```
Full log is available here: http://fedora.riscv.rocks/kojifiles/work/tasks/5951/315951/build.log

**Comment by squeek502** [comment]
Thanks for the report. `uv_tcp_close_reset` was added in Libuv 1.32.0, but the test is not being skipped when Luv is linked against earlier versions of Libuv. Will fix that when I get a chance.

**Comment by davidlt** [comment]
I didn't notice that libuv is not up to date. I will update it to a proper version and try again.

**Comment by squeek502** [comment]
Luv intends to support linking against older Libuv versions, so this is still a bug.

**Comment by davidlt** [comment]
The build was successful: http://fedora.riscv.rocks/koji/taskinfo?taskID=315978
