### ISSUE TITLE
check list for release v1.34.1

### ISSUE THREAD

**Issue by zhaozg** [luvit/luv#449]
- [x] submodule update [lua](https://github.com/luvit/luv/pull/448/commits/2f2334b18a806b14f5af93d211981b2fb0568cf6)/[luajit](https://github.com/luvit/luv/pull/448/commits/00465e0f11980b2de2fb8c8abc71a7ae68dc661a)/[libuv](https://github.com/luvit/luv/pull/448/commits/fb49cbaebfeb55b8f748b52c8e5e05c04e53ba2c)
- [x] all test pass.
- [x] missing new apis.  Finished in https://github.com/luvit/luv/pull/450
  - [x] uv_tty_set_vterm_state, in https://github.com/luvit/luv/pull/450/commits/b2c3ab0ae7866c5de00314d78622eb99c967ecb5, but all tty test miss
  - [x] uv_tty_get_vterm_state, in https://github.com/luvit/luv/pull/450/commits/b2c3ab0ae7866c5de00314d78622eb99c967ecb5
  - [x] uv_fs_mkstemp, in https://github.com/luvit/luv/pull/450/commits/4e667d386629818ddd1ffa54f57d68fea4b3d2f9
  - [x] uv_random, in https://github.com/luvit/luv/pull/450/commits/3656f453588e2d3955d2113f718db31f699201ee
  - [x] uv_sleep, in https://github.com/luvit/luv/pull/448/commits/fbac0b173ecba2c8f6dc2f177fc0f008d2ba61c6
- [x] update version

And final, public tag

**Comment by squeek502** [comment]
I'll work on the `uv_random` binding.

**Comment by zhaozg** [comment]
Release [1.34.1-0](https://github.com/luvit/luv/releases/tag/1.34.1-0)

**Comment by SinisterRectus** [comment]
Good stuff, and thank you for keeping the docs updated!

**Comment by SinisterRectus** [comment]
Luarocks release? https://luarocks.org/modules/creationix/luv

**Comment by squeek502** [comment]
Looks like the deploy failed due to

`The program 'luarocks' is currently not installed.`

https://travis-ci.org/luvit/luv/jobs/638441659#L848-L851

Not sure why that would be.
