### ISSUE TITLE
SHAREDLIBS_INSTALL_INC_DIR not set

### ISSUE THREAD

**Issue by teto** [luvit/luv#463]
Still trying to package libuv on nixos
```
-- Lua: using information from luarocks
-- LUA_LIBDIR: 
-- LUA_INCDIR: /nix/store/491m3i5n0l92aar68hjy0zv61yw11jc6-luajit-2.1.0-beta3/include/luajit-2.1
-- LUA: /nix/store/491m3i5n0l92aar68hjy0zv61yw11jc6-luajit-2.1.0-beta3/bin/luajit
-- Lua library: LUA_LIBRARIES-NOTFOUND
-- path 
CMake Error at CMakeLists.txt:253 (install):
  install FILES given no DESTINATION!
```
Going through the various steps, `SHAREDLIBS_INSTALL_INC_DIR` ,  I find `set(SHAREDLIBS_INSTALL_INC_DIR "${INSTALL_INC_DIR}")` but INSTALL_INC_DIR is possibly never set (hence the error), whereas   INSTALL_LIB_DIR defaults to ${LIBDIR}. Would be cool to have a nice default.

**Comment by squeek502** [comment]
Ok, I think I understand now. Luarocks doesn't provide an install path for headers, so we need to use the default system install paths for those when building shared/static libs.
