### ISSUE TITLE
luv_work_ctx_t async

### ISSUE THREAD

**Issue by SinisterRectus** [luvit/luv#467]
`luv_work_ctx_t` defines an `async` handle and `async_cb` reference...
https://github.com/luvit/luv/blob/ecfed21b41c01b1dfdb5b2924c10fc659c3de65b/src/work.c#L20-L29

`luv_new_work` optionally initializes this handle with a callback...
https://github.com/luvit/luv/blob/ecfed21b41c01b1dfdb5b2924c10fc659c3de65b/src/work.c#L177-L179

but as far as I can tell, the handle is never exposed to Lua. Am I missing something here?

**Comment by zhaozg** [comment]
Yes, you are right, that code should be remove, and I found  a associated bug .

So I'll deal that.
