### ISSUE TITLE
life: anti 2019-nCoV

### ISSUE THREAD

**Issue by zhaozg** [luvit/luv#469]
Hi @luvit/luvit-admin ,   If the face-mask is in short supply, please tell me, I can mail some to help you.

email: zhaozg@aliyun.com, zhaozg@gmail.com

**Comment by creationix** [comment]
Thanks @zhaozg, but I and my family have instead been in home isolation for the last few weeks instead.  I'm lucky enough to work from home and so don't need to go out for much.

**Comment by Kami** [comment]
Thanks for the offer from my side as well.
