### ISSUE TITLE
The callback of queue_work  is not running in lua main thread

### ISSUE THREAD

**Issue by scolfer** [luvit/luv#483]
In  luv_new_work function :
ctx->L = L;
Maybe it could be change to
ctx->L = luv_state(L);

**Comment by SinisterRectus** [comment]
Can you give an example of the Lua code that you are trying to run?

**Comment by scolfer** [comment]
local uv = require("luv")
local co = coroutine.create(function()
    local c = coroutine.running()
    local work = uv.new_work(function()
        -- do something
    end, function()
        -- when call to resume, will occur error(can not resume the running coroutine)
        coroutine.resume(c)
    end)
    work:queue_work()
    coroutine.yield()
end)
coroutine.resume(co)

**Comment by scolfer** [comment]
I think it's the same problem with issue [#329 ](https://github.com/luvit/luv/issues/329)

**Comment by zhaozg** [comment]
Thank you very much.
