### ISSUE TITLE
Lua 5.4

### ISSUE THREAD

**Issue by SinisterRectus** [luvit/luv#497]
Lua 5.4.0 is nearing a final release. It is currently at [rc3](http://lua-users.org/lists/lua-l/2020-05/msg00043.html).

Our supported Lua versions according to our rockspec is `lua >= 5.1`. Does this imply that 5.4 is supported on release? If so, think we should should look at whether that is true. I'm not sure if there are any compatibility changes that will affect us.

**Comment by squeek502** [comment]
Would definitely be nice to start testing 5.4 in CI.

**Comment by SinisterRectus** [comment]
Lua 5.4 has formally released since opening this issue. https://www.lua.org/manual/5.4/readme.html

**Comment by SinisterRectus** [comment]
Looks like #515 is merged. Are the build issues fixed? Should we make a 1.14.0 release?

**Comment by zhaozg** [comment]
> Looks like #515 is merged. Are the build issues fixed? Should we make a 1.40.0 release?

YES

**Comment by squeek502** [comment]
I'd like to finish up #487 and merge it before releasing 1.40.0. Will try to do that soon.

**Comment by zhaozg** [comment]
Anyone need to do before a new release

**Comment by SinisterRectus** [comment]
There are some open issues. #503 / #505 / #506. Not sure how easy those are to fix.
