### ISSUE TITLE
Error when installing using luarocks using Lua 5.4.0

### ISSUE THREAD

**Issue by leonsal** [luvit/luv#514]
Hi,

Luarocks reports the following error when installing using lua 5.4.0:
```error "unsupported Lua version (i.e. not Lua 5.1, 5.2, or 5.3)```

Any estimate when compatibility with lua 5.4.0 will be implemented ?
Regards.

**Comment by squeek502** [comment]
Related: https://github.com/luvit/luv/issues/497

**Comment by squeek502** [comment]
I think your specific error is due to an older Luarocks version, though, since our rockspec specifies `>= 5.1`, which should include 5.4. Updating your Luarocks might fix this error, but I'm not sure if Luv works properly with 5.4 yet.

**Comment by smackesey** [comment]
I also have this problem (and am using most recent luarocks). The error pops up after it looks like luv finished building. Any known workaround? I tried running the command in #515:

```
LUA_DIR=/path/to/lua-5.4.0/src cmake .. -DWITH_LUA_ENGINE=Lua -DLUA_BUILD_TYPE=System
```

But it seems to ignore my LUA_DIR and just finds my lua-5.3.5 installation in /usr/local. Note that my lua-5.4 is elsewhere, I'm on MacOS and the /usr/local luas come from homebrew, which doesn't yet include lua 5.4 (I have lua 5.4 through [asdf](https://github.com/asdf-vm/asdf). I'm not very skilled in building/cmake etc so I could be missing something obvious.

**Comment by squeek502** [comment]
Lua 5.4 support should be fixed in the latest versions. Please re-open if there is still an issue.
