### ISSUE TITLE
fs_symlink and fs_copyfile don't fail when flags param is wrong

### ISSUE THREAD

**Issue by squeek502** [luvit/luv#529]
Related to https://github.com/luvit/lit/pull/280, this type of error is harder to identify because currently the symlink/copyfile functions accept a function in the flags argument without failing. I think there are two options here:

1. Error when the flags argument is an unexpected type
2. Treat the 3rd argument as the callback if we detect that the flags argument has been omitted

I haven't double-checked, but I feel like there's precedent for both of these options in our current bindings. Not sure which would be better, but I think either of them is better than the current silent failure.

**Comment by creationix** [comment]
EIther option is about the same amount of code, so it's mostly a style question.  If we expect people to ever write code directly against luv, then the second option is better I think.
