### ISSUE TITLE
Why stream handle is 128 in the example tcp echo server?

### ISSUE THREAD

**Issue by kuator** [luvit/luv#547]
Why stream handle is 128 in the example tcp echo server? I thought stream handle is the same as a socket file descriptor
```
  server:listen(128, function(err)
    -- Make sure there was no problem setting up listen
    assert(not err, err)

    -- Accept the client
    local client = uv.new_tcp()
    server:accept(client)

    on_connection(client)
  end)
```

**Comment by squeek502** [comment]
Note that this is using `server:listen()` which means that `server` is the implicit first parameter. That is, it's the same as doing `uv.listen(server, 128, function(err) ... end)`. So, in this case, the 128 is the `backlog` parameter.

Relevant docs:
- [Functions vs Methods](https://github.com/luvit/luv/blob/master/docs.md#functions-vs-methods)
- [`uv.listen`](https://github.com/luvit/luv/blob/master/docs.md#uvlistenstream-backlog-callback)

**Comment by kuator** [comment]
Thank you!
