### ISSUE TITLE
nmake not working with prebuilt lua dlls

### ISSUE THREAD

**Issue by tDwtp** [luvit/luv#549]
I only use the Build Tools in the CLI and do not have Studio installed.
For building I use the command:
```
cmake . -DLUA_BUILD_TYPE=System -DWITH_LUA_ENGINE=Lua -DLUA_INCLUDE_DIR=S:\Workspace\tool\amd64\lua\5X\include -DLUA_LIBRARIES=S:\Workspace\tool\amd64\lua\5X\lib
```
(-H. and -Bbuild as seen in mscvcbuild.bat can be added if wanted, but wont make a difference)
Lua is detected properly and includes are set, but i have to manually add the librtary paths to compile with nmake via:
```
link /nologo @CMakeFiles\luv.dir\objects1.rsp /out:luv.dll /implib:luv.lib /pdb:S:\Workspace\Language\Lua\luv\luv-master\luv.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL /LIBPATH:S:\Workspace\tool\amd64\lua\5X\lib lua5X.lib deps\libuv\uv_a.lib psapi.lib user32.lib advapi32.lib iphlpapi.lib userenv.lib ws2_32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\luv.dir/intermediate.manifest CMakeFiles\luv.dir/manifest.res
```
Note that it wont add `/LIBPATH:S:\Workspace\tool\amd64\lua\5X\lib lua5X.lib` automatically (right before the `*.lib` listings start).
X can be replaced for version 5.1 (51) to 5.4 (54) and it *could* compile if the library path would be set somewehre/how.

I am not sure where to add the library folder for properly building luv.dll or if its a bug. I guessed that `-DLUA_LIBRARIES=...` is the way to go, but it does not work.

**Comment by squeek502** [comment]
I believe LUA_LIBRARIES should be the path to the file, not the path to the directory, e.g.

```
-DLUA_LIBRARIES=S:\Workspace\tool\amd64\lua\5X\lib\lua5X.lib
```

**Comment by tDwtp** [comment]
Yes, that was it, It needs to be the file.
I am way to used to it being a directory.
