### ISSUE TITLE
Crash when passing a lua object as thread argument

### ISSUE THREAD

**Issue by erw7** [luvit/luv#564]
The main thread will crash if I pass a table, etc. as an argument to the thread, as shown below.

```
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2021 Mike Pall. https://luajit.org/
JIT: ON SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> uv=require'luv'
> t=uv.new_thread(function(tbl) print(tbl) end, {})
Error: thread arg not support type 'table' at 2> Error: thread arg not support type table at 1Uncaught Error: attempt to call a nil value
```

This problem can be fixed with the following patch.

```diff
diff --git a/src/thread.c b/src/thread.c
index b130593..50ed7e2 100644
--- a/src/thread.c
+++ b/src/thread.c
@@ -201,6 +201,7 @@ static int luv_thread_arg_push(lua_State* L, luv_thread_arg
_t* args, int flags)
     default:
       fprintf(stderr, "Error: thread arg not support type %s at %d",
         lua_typename(L, arg->type), i + 1);
+      lua_pushnil(L);
     }
     i++;
   };
```

However, I think it would be better to change the following part to `return lua_error(L)`. If we call `lua_error` with `luv_thread_arg_set`, will there be a memory leak or some other problem? I have not created a PR because I do not know which modification is preferable for us.
 
https://github.com/luvit/luv/blob/b2572ecf988185b9763965c590f6edbb2bc9b6c3/src/thread.c#L105-L110

**Comment by zhaozg** [comment]
> However, I think it would be better to change the following part to return lua_error(L). If we call lua_error with luv_thread_arg_set, will there be a memory leak or some other problem? I have not created a PR because I do not know which modification is preferable for us.

lua_error is not a good idea, because luv_thread_arg_push maybe called in OS main/child thread or  threadpools. We should keep all threads run continue, especially in threads, or threadpools size will reduces.

So just  add  `lua_pushnil(L)` in my option.

**Comment by zhaozg** [comment]
ping @squeek502 Please help  us do a new release.

**Comment by squeek502** [comment]
Will do!

**Comment by squeek502** [comment]
https://github.com/luvit/luv/releases/tag/1.42.0-0
