### ISSUE TITLE
Uncaught Error in work callback: pool:1:

### ISSUE THREAD

**Issue by Ajnasz** [luvit/luv#567]
Hi!

I'm just experimenting with this library, and when I try to execute the [thread pool work scheduling](https://github.com/luvit/luv/blob/master/docs.md#thread-pool-work-scheduling) example, I get the following error:

> Uncaught Error in work callback: pool:1: unexpected symbol near '`'
> Uncaught Error: Uncaught Error: function can't be work entry
> 
> stack traceback:
>         [C]: in ?
> Uncaught Error: attempt to call a nil value
> stack traceback:
>         [C]: in ?

My lua version is `Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio`
I installed luv with luarocks

> sudo luarocks install luv
> ...
> luv 1.42.0-0 is now installed in /usr/local (license: Apache 2.0)

The entire code I try to run is the following:

```lua
local uv = require("luv")
local function work_callback(a, b)
  return a + b
end

local function after_work_callback(c)
  print("The result is: " .. c)
end

local work = uv.new_work(work_callback, after_work_callback)

uv.queue_work(work, 1, 2)
```

Can you give me some advice, how to deal with the issue?

Thanks

**Comment by squeek502** [comment]
You're missing a `uv.run()` call at the end to start the event loop

**Comment by Ajnasz** [comment]
Right, thanks!
