### ISSUE TITLE
Release 1.43.0 checklist

### ISSUE THREAD

**Issue by zhaozg** [luvit/luv#580]
- [ ] update https://github.com/luvit/luv/blob/master/luv-scm-0.rockspec#L10
- [ ] update version in source files
- [ ] tag
- [ ] publish

**Comment by squeek502** [comment]
Sorry, tagged a release before I saw this. The only thing that won't be included is https://github.com/luvit/luv/blob/master/luv-scm-0.rockspec#L10, which we can release as `1.43.0-1`

**Comment by zhaozg** [comment]
That's a not tiny thing, just add 5.4. We do that next release.
