### ISSUE TITLE
Libuv 1.44.0 uv_os_get_passwd signed -> unsigned change breaks our binding

### ISSUE THREAD

**Issue by zhaozg** [luvit/luv#589]
After libuv version v1.44.0, we got two alerts. [see](https://lgtm.com/projects/g/luvit/luv/alerts/?mode=list).

**Comment by squeek502** [comment]
Relevant Libuv change: https://github.com/libuv/libuv/pull/3476

Might need to change those comparisons for `1.44.0` and above only, so that we keep compatibility when building against earlier Libuv versions.
