### ISSUE TITLE
Test is failing on Fedora (luv 1.43.0.0)

### ISSUE THREAD

**Issue by cryptomilk** [luvit/luv#594]
Hey,

a threadpool test is failing on Fedora if I build in koji:

```
ok 110 work - test threadpool with async
1
2
3
4
5
7
8
ok 111 work - test threadpool with coro
ok 112 work - test threadpool with invalid argument
Uncaught Error: Error: thread arg not support type 'table' at 1
stack traceback:
	[C]: ?
ok 113 work - test threadpool with invalid return value
#1 failed test
  In	uv_thread_t: 0x7fc5ae030640
6
```

https://koji.fedoraproject.org/koji/taskinfo?taskID=85765666

How can I provide more detailed information to understand the issue?
Note that Fedora rawhide has already libuv-devel 1.44.0 and it uses lua-5.1.

**Comment by squeek502** [comment]
I believe this is the test that's failing:

```
  timeout (could be caused by firewall settings)
  ./lib/tap.lua:66: Found 1 unexpected call
  stack traceback:
  	[C]: in function 'error'
  	./lib/tap.lua:66: in function <./lib/tap.lua:48>
  	[C]: in function 'xpcall'
  	./lib/tap.lua:48: in function 'run'
  	./lib/tap.lua:146: in function 'tap'
  	tests/run.lua:23: in main chunk
  	[C]: ?
not ok 106 udp - udp multicast join ipv6
```

This is a known issue with the default `firewalld` settings of Fedora, see https://github.com/luvit/luv/issues/539

You will likely need to disable or skip that particular test.

**Comment by cryptomilk** [comment]
Can you tell the testsuite it to stop immediately when an error occurs?

**Comment by squeek502** [comment]
There's no support for that currently, no.

**Comment by cryptomilk** [comment]
Closing the bug, package on Fedora updated.
