### ISSUE TITLE
fs_access does not accept a mode for `F_OK`

### ISSUE THREAD

**Issue by beardedsakimonkey** [luvit/luv#611]
Hi, I was looking to check for existence of a file, and it seems like that's what [access(2)](https://man7.org/linux/man-pages/man2/access.2.html)'s F_OK mode is for.  However, it seem's like luv's fs_access function doesn't allow such a mode.  Is there a reason for this?
Thanks

**Comment by squeek502** [comment]
I believe `F_OK` is defined as 0 so it's always 'set', so you can call `fs_access` with only `F_OK` by passing in either `""` as the mode or `0`.
