### ISSUE TITLE
uv.fs_scandir skips dotfiles

### ISSUE THREAD

**Issue by haolian9** [luvit/luv#612]
(sorry if i have opened a upstream issue here.)

in my use, uv.fs_scandir and uv.fs_scandir_next do not return files startswith `.`, i can neither find a flag in their function signature. is this feature addable?

**Comment by truemedian** [comment]
This is a libuv limitation, see [https://docs.libuv.org/en/v1.x/fs.html#c.uv_fs_scandir_next]:

> Note: Unlike *scandir*(3), this function does not return the “.” and “..” entries.

**Comment by squeek502** [comment]
To be clear, do you mean `.` and `..` or files with a dot prefix (e.g. `.something`)?

**Comment by haolian9** [comment]
thanks!

**Comment by haolian9** [comment]
oh, sorry i just missed your comment. i mean to "files with a dot prefix (e.g. .something)".

**Comment by squeek502** [comment]
That should work.

```lua
local uv = require('luv')

assert(uv.fs_scandir('.', function(err, req)
  assert(not err)
  local function iter()
    return uv.fs_scandir_next(req)
  end
  for name, ftype in iter do
    print(name, ftype)
  end
end))

uv.run()
```

gives me:

```
.ci	directory
.clang-format	file
.clangd	file
.editorconfig	file
.git	directory
.github	directory
.gitignore	file
.gitmodules	file
CMakeLists.txt	file
LICENSE.txt	file
Makefile	file
README.md	file
appveyor.yml	file
build	directory
cmake	directory
deps	directory
docs.md	file
... (truncated)
```

**Comment by haolian9** [comment]
thanks for the example!
