### ISSUE TITLE
Please consider upgrading the minimum required version of cmake

### ISSUE THREAD

**Issue by dundargoc** [luvit/luv#616]
Compatibility with CMake < 2.8.12 will be removed from a future version of CMake. I'd like to make a request that we move the minimum required version to at least 3.0 to ensure we don't rely on deprecated features. This will also get rid of the annoying deprecation warning each time the project is built.

Please feel free to close the issue if this isn't possible or wanted.

**Comment by squeek502** [comment]
Unless there's reason not to, seems like the 'safest' thing to do would just be to set the minimum to 2.8.12.
