### ISSUE TITLE
Running commands in strings fails

### ISSUE THREAD

**Issue by miversen33** [luvit/luv#623]
Hello! I have found an interesting issue when running a command with [uv.spawn](https://github.com/luvit/luv/blob/master/docs.md#uvspawnpath-options-on_exit)

Below is an example lua script that will fail, though if you run the command in a linux shell, the command is valid. 
```lua
-- test.lua
local uv = require("luv")

local handle = nil
local on_exit = function(code, signal)
    print(string.format("Exit Code: %s", code))
    print(string.format("Exit Signal: %s", signal))
    handle:close()
end

local stdout = uv.new_pipe(false)
local stderr = uv.new_pipe(false)
-- This command `/bin/sh -c 'touch /tmp/testing.txt'` is a valid linux command, but this script fails out
local command = "/bin/sh"
local args = {"-c", "'touch /tmp/testing.txt'"}
local opts = {
    args = args,
    stdio = {nil, stdout, stderr}
}

handle, _ = uv.spawn(command, opts, on_exit)

stdout:read_start(function(err, data)
    assert(not err, err)
    print(string.format("%s", data))
end)

stderr:read_start(function(err, data)
    assert(not err, err)
    print(string.format("Error: %s", data))
end)

uv.run()
```

The above will drop the following output
```lua
$ lua test.lua 
Error: /bin/sh: line 1: touch /tmp/testing.txt: No such file or directory

Error: nil
nil
Exit Code: 127
Exit Signal: 0
```
However, this is _not_ the case when you run the command via a shell
```shell
$ /bin/sh -c 'touch /tmp/testing.txt'
$ echo $?
0
```

I assume I am doing something wrong but I dont really know. I have tried breaking the string arg up by space but I get the same error. Any ideas?

**Comment by squeek502** [comment]
Have you tried
```lua
local args = {"-c", "touch /tmp/testing.txt"}
```
(i.e. without the single quote chars)

AFAIK quote parsing is a feature of the shell and so quotes should not be included in the args table as you're able to provide each arg separately without the need for quotes.

**Comment by miversen33** [comment]
Im so very annoyed that that worked lol. I appreciate you! Thank you!
