### ISSUE TITLE
request bind v1.45.0 new features

### ISSUE THREAD

**Issue by zhaozg** [luvit/luv#646]
http://docs.libuv.org/en/v1.x/metrics.html#c.uv_metrics_info

**Comment by squeek502** [comment]
I'm working on this. Here's the full list of new stuff: https://docs.libuv.org/en/v1.x/search.html?q=1.45.0

**Comment by zhaozg** [comment]
Opps, I made a PR, https://github.com/luvit/luv/pull/649.

**Comment by squeek502** [comment]
No worries, I am working on the bindings for `uv_thread_cpuinfo`, `uv_thread_getaffinity`, `uv_thread_setaffinity`, `uv_get_available_memory`, and `uv_cpumask_size`.

**Comment by zhaozg** [comment]
@squeek502 can you help to look at this : https://github.com/luvit/luv/actions/runs/5030484708/jobs/9022947003

**Comment by squeek502** [comment]
I can't test it right now since I'm on Windows currently, but my first guess is that it's finding a regression in libuv.

**Comment by zhaozg** [comment]
Ok, I got ideas, some Mem error should be suppression.

**Comment by squeek502** [comment]
Those errors don't look like something we should suppress. `Conditional jump or move depends on uninitialised value(s)` and `Use of uninitialised value of size 8` pretty much always means there is a bug somewhere.

**Comment by squeek502** [comment]
I'm getting the [same valgrind errors in my branch](https://github.com/squeek502/luv/actions/runs/5030912773/jobs/9023649689) that only updates Libuv, so this looks like either a bug on our end or a regression on Libuv's end.

**Comment by zhaozg** [comment]
Ok, We do double check.

**Comment by squeek502** [comment]
My guess is that it's a regression in libuv. It wouldn't be the first time that our tests have found things that the libuv tests missed. I will investigate it soon.

**Comment by zhaozg** [comment]
> My guess is that it's a regression in libuv. It wouldn't be the first time that our tests have found things that the libuv tests missed. I will investigate it soon.

I add `--track-origins=yes` for valgrind in https://github.com/luvit/luv/actions/runs/5031004869/jobs/9023801782, that report `Uninitialised value`  value was created by a heap allocation in libuv side,
`uv__iou_fs_statx` call by `uv_fs_stat`, I can say https://github.com/libuv/libuv/blob/v1.x/src/unix/linux.c#L816
come from https://github.com/libuv/libuv/pull/3952,

**Comment by zhaozg** [comment]
Can you report this to libuv, I have unclear English communication ability. ☹

**Comment by squeek502** [comment]
Sure, I will make an issue in a bit.
