### ISSUE TITLE
Lua 5.4.7 update

### ISSUE THREAD

**Issue by SinisterRectus** [luvit/luv#709]
I meant to push https://github.com/luvit/luv/commit/b35a4c0cf3838909f019e75edb84b32e7e1f96ff to a fork then PR it, but I got trigger happy. Apologies.

Lua updated to [5.4.7](https://www.lua.org/versions.html) on 25 Jun 2024 and a GitHub [release](https://github.com/lua/lua/releases/tag/v5.4.7) was made available yesterday on 11 July 2024.

Some of the checks appear to be failing. If there is an issue, we can discuss it here.

**Comment by SinisterRectus** [comment]
I also now realize that I updated to the HEAD, which is 5.4.7 + 115 commits.

**Comment by SinisterRectus** [comment]
One build failure in [build (ubuntu-latest, 3.8.0, Lua)](https://github.com/luvit/luv/actions/runs/9909777545/job/27378619954):

```
lua: error loading module 'luv' from file './luv.so':
	./luv.so: undefined symbol: luaL_openselectedlibs
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: in ?
/home/runner/work/_temp/cf02c6a6-26c5-41c0-b1d5-901757cb6e08.sh: line 2: test: /home/runner/work/luv/luv: unary operator expected
Error: Process completed with exit code 2.
```

The other three failures are due to a deprecation + removal:
> The options "setpause" and "setstepmul" of the function [collectgarbage](https://www.lua.org/manual/5.4/manual.html#pdf-collectgarbage) are deprecated. You should use the new option "incremental" to set them.

The option was removed with https://github.com/lua/lua/commit/35a2fed2d1e0b95a1bfab364707e469863517085.

**Comment by truemedian** [comment]
luaL_openselectedlibs is a Lua 5.5 addition, which has yet to be released

**Comment by SinisterRectus** [comment]
Good to know. I'm working on a fix at the moment.
