### ISSUE TITLE
callbacks may longjmp out of the scope of uv.run

### ISSUE THREAD

**Issue by imzyxwvu** [luvit/luv#99]
luv calls callbacks with lua_call, which does not catch Lua errors. When Lua errors occur in callbacks, Lua will do a long jump to the last pcall on the stack and return at that level.

Then the problem came. The long jump will skip the rest code of libuv's uv_run, which is unsafe. I didn't find any statement in the libuv document which ensures it safe to do long jumps in libuv callbacks.

The best solution to get over this problem is use lua_pcall, but it does not report the stack traceback when errors occur. That means debugging will be difficult.

**Comment by creationix** [comment]
I looked at the libuv code and it appears to be safe, but I am considering a change in semantics here.  This has other weird issues where it sometimes will swallow errors.  I'm thinking something like a global error handler for uncaught exceptions at event sources.  We should be able to capture the traceback to the uv_run call.

**Comment by imzyxwvu** [comment]
Just printing the error message and making it able to set a global error handler seems to be a good solution.

> We should be able to capture the traceback to the uv_run call.

lua_pcall can set a function to collect stack status when the stack has not be unwinded.

**Comment by creationix** [comment]
After talking to the libuv authors for a while, I've learned that libuv does indeed assume callback will return and does some cleanup after the fact.  I don't think uv.run is in danger of this hazard, but other callbacks are.  We'll need to re-figure how to handle this.

**Comment by creationix** [comment]
This is now fixed.  If uncaught exceptions happen, the process will hard exit.  In practice, everyone was wrapping in a pcall or xpcall in the lua side already.
